url: "http://gswith.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "gswith.in" # the name of your site, e.g. ACME Corp.

# Google Analytics
google_analytics: G-CYZ1MME7C5
